### PR TITLE
Fixes for issues 6-7-8

### PR DESCRIPTION
**Pull request by otsakir**
Hey, 

I had some trouble at first contact with 'restserver'. I did some digging and provided some fixes. You can find brief descriptions as issues #6, #7, #8 . 

Feel free to review and merge.

Thanks

Orestis

### CODE REVIEW

**Comment by hishamhm** [comment]
@otsakir Thank you for the fixes!

I am not actively maintaining this project. Would you like to take it over and take it in any direction you'd like?

**Comment by otsakir** [comment]
Hello @hishamhm. 

Thanks for offering. Yeah, it crossed my mind. But give me some time to get my hands more dirty and get more familiar with it before  taking up any responsibilities.

**Comment by hishamhm** [comment]
No worries! In any case, I sent you an invite to give you commit access. So
feel free to push any tweaks or fixes!

>

**Comment by otsakir** [comment]
ok @hishamhm , i've seen enough. I could take over `restserver` maintainance and further development as a side task. I guess i could use this repo or my own fork. Both options work for me. 

wdyt ?

**Comment by hishamhm** [comment]
That's great to hear, thank you!

What is your luarocks.org account? I can reassign the restserver entry to
you.

Regarding the Github repo, you can use either. I'm not sure if there is any
reduced functionality in a fork repo or what is the procedure for
redirecting this one into yours as the main one. Do you have any experience
with that? Otherwise I can look it up and learn about it.

**Comment by otsakir** [comment]
Cool @hishamhm. Let's use the current repository then. No need to disturb community. I don't know how to create issues in the forked repo either.

My luarocks account is `otsakir`.

**Comment by hishamhm** [comment]
Cool! Your entry in luarocks.org is now the one that the root manifest in luarocks.org points to: https://luarocks.org/modules/otsakir/restserver

So now you can make new releases of this module using your API key and `luarocks upload`. Cheers! :tada:

**Comment by otsakir** [comment]
Thanks @hishamhm!

I'll try to the make the best use of it ;-)

**Pull request merged**
